---
# Databases backups to check
databases: []
# - name: example
#   schedule: "0 2 * * 6"
#   timeout: 14400
#   nodeSelector: {}
#   affinity: {}
#   resources:
#     limits:
#       cpu: 100m
#       memory: 256Mi
#     requests:
#       cpu: 100m
#       memory: 256Mi
#   tolerations: []
#   # name of cloud where instance will be created
#   # supported values are: "aws" and "digital-ocean"
#   cloud: "aws"
#   # user which will be used to ssh on created instance
#   # for Digital Ocean this is "root"
#   # for AWS you should check chosen AMI documentation
#   ssh_user: root
#   # kubernetes secret which contains ssh key which will be added to user on created instance (change it!)
#   # this key must be unique across all databases in the same cloud to prevent conficts
#   # during addition/deletion key through cloud API
#   # you can use RSA or ed25519 key for Digital Ocean
#   # for AWS only RSA key is supported
#   sshKeysSecretName: example-ssh-keys
#   # variables from this secret will be added as --extra-vars to ansible-playbook
#   ansibleVariablesSecretName: example-ansible-variables

ansible_backup_check:
  image:
    repository: quay.io/evl.ms/ansible-postgresql-backup-check
    tag: 20211013-alpine
    pullPolicy: IfNotPresent
