---
{{- if .Values.ruleGroups.kubernetesSystem.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "infrastructure-alerts.fullname" .) "kubernetes-system-apiserver" | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "infrastructure-alerts.namespace" . }}
  labels:
    app: {{ template "infrastructure-alerts.name" . }}
    {{- include "infrastructure-alerts.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: kubernetes-system-apiserver
    rules:
    {{- if not (has "KubeClientCertificateExpiration" .Values.ruleGroups.kubernetesSystem.disabledRules)}}
    - alert: KubeClientCertificateExpiration
      annotations:
        message: A client certificate used to authenticate to kubernetes apiserver is expiring in less than 7.0 days.
        runbook_url: {{ .Values.runbookUrl }}alert-name-kubeclientcertificateexpiration
        summary: Client certificate is about to expire.
      expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and on(job) histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 604800
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- if not (has "KubeClientCertificateExpiration" .Values.ruleGroups.kubernetesSystem.disabledRules)}}
    - alert: KubeClientCertificateExpiration
      annotations:
        message: A client certificate used to authenticate to kubernetes apiserver is expiring in less than 24.0 hours.
        runbook_url: {{ .Values.runbookUrl }}alert-name-kubeclientcertificateexpiration
        summary: Client certificate is about to expire.
      expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and on(job) histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 86400
      labels:
        severity: dangerous
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- if not (has "AggregatedAPIErrors" .Values.ruleGroups.kubernetesSystem.disabledRules)}}
    - alert: AggregatedAPIErrors
      annotations:
        message: Kubernetes aggregated API {{`{{`}} $labels.name {{`}}`}}/{{`{{`}} $labels.namespace {{`}}`}} has reported errors. It has appeared unavailable {{`{{`}} $value | humanize {{`}}`}} times averaged over the past 10m.
        runbook_url: {{ .Values.runbookUrl }}alert-name-aggregatedapierrors
        summary: Kubernetes aggregated API has reported errors.
      expr: sum by(name, namespace, cluster)(increase(aggregator_unavailable_apiservice_total[10m])) > 4
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- if not (has "AggregatedAPIDown" .Values.ruleGroups.kubernetesSystem.disabledRules)}}
    - alert: AggregatedAPIDown
      annotations:
        message: Kubernetes aggregated API {{`{{`}} $labels.name {{`}}`}}/{{`{{`}} $labels.namespace {{`}}`}} has been only {{`{{`}} $value | humanize {{`}}`}}% available over the last 10m.
        runbook_url: {{ .Values.runbookUrl }}alert-name-aggregatedapidown
        summary: Kubernetes aggregated API is down.
      expr: (1 - max by(name, namespace, cluster)(avg_over_time(aggregator_unavailable_apiservice[10m]))) * 100 < 85
      for: 5m
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- if not (has "KubeAPIDown" .Values.ruleGroups.kubernetesSystem.disabledRules)}}
    - alert: KubeAPIDown
      annotations:
        message: KubeAPI has disappeared from Prometheus target discovery.
        runbook_url: {{ .Values.runbookUrl }}alert-name-kubeapidown
        summary: Target disappeared from Prometheus target discovery.
      expr: absent(up{job="apiserver"} == 1)
      for: 15m
      labels:
        severity: dangerous
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- if not (has "KubeAPITerminatedRequests" .Values.ruleGroups.kubernetesSystem.disabledRules)}}
    - alert: KubeAPITerminatedRequests
      annotations:
        message: The kubernetes apiserver has terminated {{`{{`}} $value | humanizePercentage {{`}}`}} of its incoming requests.
        runbook_url: {{ .Values.runbookUrl }}alert-name-kubeapiterminatedrequests
        summary: The kubernetes apiserver has terminated {{`{{`}} $value | humanizePercentage {{`}}`}} of its incoming requests.
      expr: sum(rate(apiserver_request_terminations_total{job="apiserver"}[10m]))  / (  sum(rate(apiserver_request_total{job="apiserver"}[10m])) + sum(rate(apiserver_request_terminations_total{job="apiserver"}[10m])) ) > 0.20
      for: 5m
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
{{- end }}
