---
{{- if .Values.ruleGroups.configReloaders.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "infrastructure-alerts.fullname" .) "config-reloaders" | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "infrastructure-alerts.namespace" . }}
  labels:
    app: {{ template "infrastructure-alerts.name" . }}
    {{- include "infrastructure-alerts.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: config-reloaders
    rules:
    {{- if not (has "ConfigReloaderSidecarErrors" .Values.ruleGroups.configReloaders.disabledRules)}}
    - alert: ConfigReloaderSidecarErrors
      annotations:
        message: 'Errors encountered while the {{`{{`}}$labels.pod{{`}}`}} config-reloader sidecar attempts to sync config in {{`{{`}}$labels.namespace{{`}}`}} namespace.

          As a result, configuration for service running in {{`{{`}}$labels.pod{{`}}`}} may be stale and cannot be updated anymore.'
      expr: max_over_time(reloader_last_reload_successful{namespace=~".+"}[5m]) == 0
      for: 10m
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
{{- end }}
