{{- range .Values.databases }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/ssh-auth
metadata:
  labels: {{ include "cloudsql-backup-check.labels" $ | nindent 4 }}
  name: {{ .name }}-ssh-key
data:
  ssh-privatekey: {{ .ssh.private_key | b64enc }}
  ssh-publickey: {{ .ssh.public_key | b64enc }}
{{ end }}
