---
{{- if .Values.ruleGroups.alertmanager.enabled }}
{{- $alertmanagerJob := .Values.alertmanagerJob }}
{{- $namespace := printf "%s" (include "infrastructure-alerts.namespace" .) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "infrastructure-alerts.fullname" .) "alertmanager.rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "infrastructure-alerts.namespace" . }}
  labels:
    app: {{ template "infrastructure-alerts.name" . }}
    {{- include "infrastructure-alerts.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: alertmanager.rules
    rules:
    {{- if not (has "AlertmanagerConfigInconsistent" .Values.ruleGroups.alertmanager.disabledRules) }}
    - alert: AlertmanagerConfigInconsistent
      annotations:
        message: 'The configuration of the instances of the Alertmanager cluster `{{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.service {{`}}`}}` are out of sync.

          {{`{{`}} range printf "alertmanager_config_hash{namespace=\"%s\",service=\"%s\"}" $labels.namespace $labels.service | query {{`}}`}}

          Configuration hash for pod {{`{{`}} .Labels.pod {{`}}`}} is "{{`{{`}} printf "%.f" .Value {{`}}`}}"

          {{`{{`}} end {{`}}`}}

          '
      expr: count by(namespace,service) (count_values by(namespace,service) ("config_hash", alertmanager_config_hash{job="{{ $alertmanagerJob }}",namespace="{{ $namespace }}"})) != 1
      for: 5m
      labels:
        severity: dangerous
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- if not (has "AlertmanagerFailedReload" .Values.ruleGroups.alertmanager.disabledRules) }}
    - alert: AlertmanagerFailedReload
      annotations:
        message: Reloading Alertmanager's configuration has failed for {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod{{`}}`}}.
      expr: alertmanager_config_last_reload_successful{job="{{ $alertmanagerJob }}",namespace="{{ $namespace }}"} == 0
      for: 10m
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- if not (has "AlertmanagerMembersInconsistent" .Values.ruleGroups.alertmanager.disabledRules) }}
    - alert: AlertmanagerMembersInconsistent
      annotations:
        message: Alertmanager has not found all other members of the cluster.
      expr: |-
        alertmanager_cluster_members{job="{{ $alertmanagerJob }}",namespace="{{ $namespace }}"}
          != on (service) GROUP_LEFT()
        count by (service) (alertmanager_cluster_members{job="{{ $alertmanagerJob }}",namespace="{{ $namespace }}"})
      for: 5m
      labels:
        severity: dangerous
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    {{- end }}
{{- end }}
