---
apiVersion: v2
appVersion: "1.0.0"
description: Creating resourses for preview apps
name: preview-apps
version: 0.4.0
maintainers:
  - name: Ilya Cherepanov
    email: deponian@evilmartians.com

dependencies:
- name: kubernetes-replicator
  repository: https://helm.mittwald.de
  version: 2.10.0
