---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-version-exporter.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "argocd-version-exporter.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argocd-version-exporter.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "argocd-version-exporter.fullname" . }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.targetPort }}
            protocol: TCP
        env:
          - name: PORT
            value: {{ .Values.service.targetPort | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{ toYaml . | nindent 8 }}
      {{- end }}
