apiVersion: v1
kind: Service
metadata:
  name: {{ template "argocd-version-exporter.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "argocd-version-exporter.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{ toYaml .Values.service.labels | trim | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "argocd-version-exporter.selector" . | nindent 4 }}