{{ if .Values.issuer.stagingServer.enabled }}
{{ $name := printf "%s-%s" (include "cert-manager-issuers.name" .) "staging" | quote }}
---
apiVersion: {{ .Values.issuer.apiVersion }}
kind: ClusterIssuer
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.stagingServer.url }}
    privateKeySecretRef:
      name: {{ $name }}
    solvers:
    {{- with .Values.solvers }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{ end }}
