---
apiVersion: scheduling.k8s.io/v1
description: Default priority class
kind: PriorityClass
metadata:
  name: overprovisioning
value: -2
globalDefault: false
description: "Priority class used by overprovisioning"
