apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-exporter
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: argocd-exporter
  podMetricsEndpoints:
  - port: http