---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: argocd-exporter
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-exporter
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-exporter
subjects:
  - kind: ServiceAccount
    name: argocd-exporter
    namespace: argocd
