---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  secretName: {{ .Values.certificate.name }}
  issuerRef: 
    kind: Issuer
    name: {{ .Values.issuer.name }}
  commonName: "*.{{ .Values.dnsZone }}"
  dnsNames:
    - "*.{{ .Values.dnsZone }}"
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"
      replicator.v1.mittwald.de/replication-allowed-namespaces: "preview-[0-9]+"
