---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: preview-apps-wildcard
spec:
  secretName: preview-apps-wildcard
  issuerRef: 
    kind: Issuer
    name: preview-apps
  commonName: "*.{{ .Values.dnsZone }}"
  dnsNames:
    - "*.{{ .Values.dnsZone }}"
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"
      replicator.v1.mittwald.de/replication-allowed-namespaces: "preview-[0-9]+"
