---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.server }}
    privateKeySecretRef:
      name: {{ .Values.issuer.name }}
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.dnsZone }}
      dns01: {{ .Values.issuer.dns01 | toYaml | nindent 8 }}
