---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: preview-apps
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: {{ .Values.issuer.server }}
    privateKeySecretRef:
      name: preview-apps
    solvers:
    - selector:
        dnsZones:
          - {{ .Values.dnsZone }}
      dns01: {{ .Values.issuer.dns01 | toYaml | nindent 8 }}
