{{ if .Values.legacy }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: balanced
parameters:
  type: pd-balanced
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
{{ end }}
{{ if .Values.csi }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: balanced-zonal
parameters:
  type: pd-balanced
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: balanced-regional
parameters:
  type: pd-balanced
  replication-type: regional-pd
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{ end }}