{{ if .Values.csi }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: extreme-zonal
parameters:
  type: pd-extreme
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: extreme-regional
parameters:
  type: pd-extreme
  replication-type: regional-pd
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{ end }}