{{ if .Values.legacy }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
{{ end }}
{{ if .Values.csi }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-zonal
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: pd-standard
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-regional
parameters:
  type: pd-standard
  replication-type: regional-pd
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{ end }}