---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-zonal
parameters:
  type: pd-standard
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-regional
parameters:
  type: pd-standard
  replication-type: regional-pd
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
