nameOverride: "kuvaq"
fullnameOverride: "kuvaq"

image:
  repository: appimage
  tag: latest
  pullPolicy: IfNotPresent
  # add imagePullSecrets to deployments spec if true
  pullSecret: true

rails:
  # ENV['RAILS_ENV']
  rails_env: "test"

  # ENV['RAILS_MAX_THREADS']
  rails_max_threads: 4

  # ENV['WEB_CONCURRENCY']
  web_concurrency: 3

  # ENV['DATABASE_POOL']
  database_pool: 5

components:
  web:
    replicas: 1

    readinessProbe: /
    livenessProbe: /
    livenessProbePort: 5000

    resources:
      limits:
        cpu: 1
        memory: 1024Mi
      requests:
        cpu: 1
        memory: 512Mi

    service:
      type: ClusterIP
      port: '5000'
    metrics:
      type: ClusterIP
      port: '9394'

    strategy:
      maxSurge: 1
      maxUnavailable: 0

    hostnames:
      - kuvaq.lan

    ingress:
      enabled: true
      letsEncrypt: true
      className: ""
      annotations:
        kubernetes.io/ingress.class: nginx

    podDisruptionBudget:
      enabled: true
      minAvailable: 50%

    serviceMonitor: true

    nodeSelector: {}
    tolerations: []
    affinity: {}

  sidekiq:
    replicas: 5

    service:
      type: ClusterIP
      port: '5000'
    metrics:
      type: ClusterIP
      port: '9394'

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi

    podDisruptionBudget:
      enabled: true
      minAvailable: 25%

    serviceMonitor: true

    nodeSelector: {}
    tolerations: []
    affinity: {}

  maintenance:
    enabled: false
    predictedFinishTime: "soon" # ISO8601 timestamp is expected here
