{{- range .Values.apps }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: {{ .name }}-backup-create
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ .name }}-cloudsql-backup-create
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name }}-backup-create
        app.kubernetes.io/instance: {{ $.Release.Name }}
      name: cloudsql-backup-create
    spec:
      activeDeadlineSeconds: {{ .backupTimeout | default 7200 }}
      backoffLimit: 3
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .name }}-backup-create
            app.kubernetes.io/instance: {{ $.Release.Name }}
        spec:
          containers:
          - name: restic
            image: "{{ $.Values.restic.image.repository }}:{{ $.Values.restic.image.tag }}"
            imagePullPolicy: {{ $.Values.restic.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - '/usr/local/bin/pg_dump --verbose --format=c | /usr/bin/restic backup --host={{ .name }}-backup --verbose --stdin --stdin-filename="${PGDATABASE}.dump"'
            envFrom:
            - secretRef:
                name: {{ .name }}-restic-credentials
            - secretRef:
                name: {{ .name }}-postgres-credentials
            volumeMounts:
            - name: config-files
              mountPath: /config
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          volumes:
          - name: config-files
            secret:
              secretName: {{ .name }}-config-files
          {{- with $.Values.restic.affinity }}
          affinity:
          {{- toYaml . | nindent 12 }}
          {{- end }}
{{- if .nodeSelector }}
          nodeSelector:
{{ toYaml .nodeSelector | indent 12 }}
{{- end }}
{{- if .tolerations }}
          tolerations:
{{ toYaml .tolerations | indent 12 }}
{{- end }}
  schedule: {{ .backupSchedule }}
  successfulJobsHistoryLimit: 3
  suspend: false
{{ end }}
