{{- range .Values.apps }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: {{ .name }}-backup-create
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ .name }}-postgres-credentials
data:
  {{- range $key, $value := .postgres_credentials }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{ end }}
