apiVersion: v2
appVersion: 1.16.1
version: 0.1.0
description: Lightweight connection pooler for PostgreSQL
home: https://pgbouncer.github.io/
maintainers:
- email: deponian@evilmartians.com
  name: Ilya Cherepanov
- email: ilya.nemakov@evilmartians.com
  name: Ilya Nemakov
- email: agon.smith@gmail.com
  name: Kir Kuznetsov
name: pgbouncer
sources:
- https://github.com/pgbouncer/pgbouncer
- https://github.com/larseen/pgbouncer_exporter
dependencies:
- name: application-library
  version: "0.3.*"
  repository: "https://helm.evilmartians.net"