{{- if .Values.proxy.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-cloudsql-proxy
  labels:
    app.kubernetes.io/kind: proxy
{{ include "cloudsql-backup.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudsql-backup.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/kind: proxy
        app.kubernetes.io/name: {{ include "cloudsql-backup.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.proxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: cloudsql-proxy
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          command:
          - /cloud_sql_proxy
          - -instances={{ .Values.proxy.instances }}=tcp:0.0.0.0:5432
          - -credential_file=/secrets/cloudsql/credentials.json
          ports:
            - name: pgsql
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /secrets/cloudsql/
            name: cloudsql-proxy-credentials
            readOnly: true
      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: cloudsql-proxy-credentials
          secret:
            defaultMode: 420
            secretName: {{ .Values.proxy.secretName }}
{{- end }}
