{{- range .Values.apps }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .name }}-config-files
  labels:
    app.kubernetes.io/name: {{ .name }}-{{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
data:
  {{- range $key, $value := .configFiles }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{ end }}
