{{- range .Values.databases }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels: {{ include "cloudsql-backup-check.labels" $ | nindent 4 }}
  name: {{ .name }}-ansible-variables
stringData:
  variables.yml: |
    {{- range $key, $value := .ansible_variables }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{ end }}
