{{- $currentType := set . "currentType" "pgbouncer" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.templateLabels" . | nindent 6 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.pgbouncer.listen_port }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: {{ .Values.exporter.listen_port }}
      targetPort: {{ .Values.exporter.listen_port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "app.templateSelector" . | nindent 4 }}
