{{- if .Values.exporter.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{ toYaml .Values.exporter.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  endpoints:
    - honorLabels: true
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  targetLabels:
    - app
    - release
{{- end }}
