apiVersion: v2
appVersion: "0.16.5"
description: A Helm chart for periodical backup of cloud postgresql
name: cloudsql-backup
version: 0.9.0
maintainers:
  - name: Kirill Kuznetsov
    email: kir@evilmartians.com
  - name: Ilya Cherepanov
    email: deponian@evilmartians.com
