# Applications to backup
apps: []
# - name: example
#   backupSchedule: "0 2 * * *"
#   backupTimeout: 7200
#   cleanupSchedule: "0 5 * * *"
#   cleanupTimeout: 7200
#   checkSchedule: "0 12 * * *"
#   checkTimeout: 3600
#   pruneSchedule: "0 20 * * *"
#   pruneTimeout: 14400
#   unlockSchedule: "0 20 * * *"
#   unlockTimeout: 60
#   nodeSelector: {}
#   resources:
#     limits:
#       cpu: 1
#       memory: 1Gi
#     requests:
#       cpu: 1
#       memory: 1Gi
#   tolerations: []
#   keep:
#     last: 5
#     within: 1m
#   resticCredentialsSecretName: example-restic-credentials
#   postgresCredentialsSecretName: example-postgres-credentials
#   configFilesSecretName: example-config-files

# Enables and configures a CloudSQL proxy instance.
# Use it if you do not have a private-network-connected PG db instance.
proxy:
  enabled: false
  image:
    repository: gcr.io/cloudsql-docker/gce-proxy
    tag: 1.16
    pullPolicy: IfNotPresent
  instances: ""
  nodeSelector: {}
  replicaCount: 1
  resources: {}
  secretName: cloudsql-proxy-credentials
  service:
    type: ClusterIP
    port: 5432
  tolerations: []
  affinity: {}

restic:
  affinity: {}
  image:
    repository: quay.io/evl.ms/pgrestic
    tag: 0.12.0-r0-13.2-alpine
    pullPolicy: IfNotPresent
  storage:
    enabled: false
    spec:
      storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Gi