---
{{- $targetNamespace := .Values.appNamespacesTarget }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "extra-alerts.fullname" .) "kubernetes-apps" | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "extra-alerts.namespace" . }}
  labels:
    app: {{ template "extra-alerts.name" . }}
    {{- include "extra-alerts.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: kubernetes-apps
    rules:
    - alert: KubePodCrashLooping
      annotations:
        description: 'Pod {{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod {{`}}`}} ({{`{{`}} $labels.container {{`}}`}}) is in waiting state (reason: "CrashLoopBackOff").'
        runbook_url: {{ .Values.runbookUrl }}alert-name-kubepodcrashlooping
        summary: Pod is crash looping.
      expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", job="kube-state-metrics", namespace=~"{{ $targetNamespace }}"}[5m]) >= 1
      for: 5m
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    - alert: KubePodCrashLoopingLong
      annotations:
        description: 'Pod: {{`{{`}} $labels.pod {{`}}`}}, namespace: {{`{{`}} $labels.namespace {{`}}`}}, container:  {{`{{`}} $labels.container {{`}}`}} restarted {{`{{`}} $value {{`}}`}} times in the last hour (at least once every 15 minutes).'
        runbook_url: {{ .Values.runbookUrl }}alert-name-kubepodcrashlooping
        summary: Pod is crash looping.
      expr: |-
        round(increase(kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace=~"{{ $targetNamespace }}"}[60m])) > 0 
          and 
        round(increase(kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace=~"{{ $targetNamespace }}"}[15m])) > 0
      for: 60m
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    - alert: KubeContainerWaiting
      annotations:
        description: pod/{{`{{`}} $labels.pod {{`}}`}} in namespace {{`{{`}} $labels.namespace {{`}}`}} on container {{`{{`}} $labels.container{{`}}`}} has been in waiting state for longer than 5 minutes.
        runbook_url: {{ .Values.runbookUrl }}alert-name-kubecontainerwaiting
        summary: Pod container waiting longer than 5 minutes
      expr: sum by ({{ range $.Values.defaultRules.additionalAggregationLabels }}{{ . }},{{ end }}namespace, pod, container, cluster) (kube_pod_container_status_waiting_reason{job="kube-state-metrics", namespace=~"{{ $targetNamespace }}"}) > 0
      for: 5m
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    - alert: KubeContainerWaiting
      annotations:
        description: pod/{{`{{`}} $labels.pod {{`}}`}} in namespace {{`{{`}} $labels.namespace {{`}}`}} on container {{`{{`}} $labels.container{{`}}`}} has been in waiting state for longer than 1 hour.
        runbook_url: {{ .Values.runbookUrl }}alert-name-kubecontainerwaiting
        summary: Pod container waiting longer than 1 hour
      expr: sum by ({{ range $.Values.defaultRules.additionalAggregationLabels }}{{ . }},{{ end }}namespace, pod, container, cluster) (kube_pod_container_status_waiting_reason{job="kube-state-metrics", namespace=~"{{ $targetNamespace }}"}) > 0
      for: 1h
      labels:
        severity: critical
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    - alert: OOMKilled
      annotations:
        description: "Container ({{`{{`}} $labels.container {{`}}`}}) OOMKilled ({{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.pod {{`}}`}})"
        summary: Container was OOMKilled.
      expr: |-
        sum by (pod, container, reason, namespace) (kube_pod_container_status_last_terminated_reason{reason="OOMKilled", namespace=~"{{ $targetNamespace }}"}) 
          * on (pod,container) 
        group_left sum by (pod, container) (changes(kube_pod_container_status_restarts_total{}[1m])) > 0
      for: 0s
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    - alert: PodMemoryUsageLimit
      annotations:
        description: 'Pod: {{`{{`}} $labels.pod {{`}}`}}, namespace: {{`{{`}} $labels.namespace {{`}}`}} memory usage {{`{{`}} printf "%.2f" $value {{`}}`}}% more than 85% of its limit for 1h'
        summary: Pod uses more than 85% of its memory limit.
      expr: |-
        sum(label_replace(container_memory_working_set_bytes{container!="", namespace=~"{{ $targetNamespace }}"}, "pod", "$1", "pod", "(.*)")) by (pod, namespace) 
          /
        sum(kube_pod_container_resource_limits{resource="memory", namespace=~"{{ $targetNamespace }}"}) by (pod,namespace) * 100 > 85
      for: 60m
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
    - alert: PodMemoryUsageLimit
      annotations:
        description: 'Pod: {{`{{`}} $labels.pod {{`}}`}}, namespace: {{`{{`}} $labels.namespace {{`}}`}} memory usage {{`{{`}} printf "%.2f" $value {{`}}`}}% more than 95% of its limit for 5m'
        summary: Pod uses more than 95% of its memory limit.
      expr: |-
        sum(label_replace(container_memory_working_set_bytes{container!="", namespace=~"{{ $targetNamespace }}"}, "pod", "$1", "pod", "(.*)")) by (pod, namespace)
          /
        sum(kube_pod_container_resource_limits{resource="memory", namespace=~"{{ $targetNamespace }}"}) by (pod,namespace) * 100 > 95
      for: 5m
      labels:
        severity: warning
        {{- if .Values.additionalRuleLabels }}
        {{- toYaml .Values.additionalRuleLabels | nindent 8 }}
        {{- end }}
